name: Test Branch CI Pipeline

on:
  push:
    branches:
      - test  # Trigger on push to the test branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.0'  # Adjust to the version you need

      # Install dependencies using Flutter (not Dart)
      - name: Install dependencies
        run: flutter pub get

      # Run tests using Flutter (not Dart)
      - name: Run tests
        run: flutter test
