name: Test Branch CI Pipeline

# Trigger the pipeline on pushes to the test branch
on:
  push:
    branches:
      - test  # This triggers the workflow on the test branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest available Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Step 3: Set up Flutter SDK
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Automatically use the latest stable version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          flutter pub get  # This installs all the dependencies defined in pubspec.yaml

      # Step 5: Run tests
      - name: Run tests
        run: flutter test  # This will run the unit tests for the Flutter project

      # Optional: Additional steps can be added here for more testing or code quality checks
